version: '3.4'

services:
  api.telegrambot:
    image: ${DOCKER_REGISTRY-}apitelegrambot
    build:
      context: .
      dockerfile: Telegram_Bot_API/Dockerfile

  db.mssql:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Q!w2e3r4t5"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"